
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.16.0",
  "versions": {
    "@openai/agents-core": "0.16.0",
    "openai": "^7.2.0"
  }
};

export default METADATA;
