
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-extensions",
  "version": "0.16.0",
  "versions": {
    "@openai/agents-extensions": "0.16.0",
    "@openai/agents-core": "workspace:*"
  }
};

export default METADATA;
